language: php
php:
  - 7.3
  - 7.2
services:
  - mysql
  - redis-server
before_script:
  - cp .env.travis .env
  - composer install
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `homestead` COLLATE `utf8_unicode_ci`;'
  - php artisan key:generate
script: vendor/bin/phpunit -c phpunit.xml